In [1]:
import pandas as pd 
from pathlib import Path
import subprocess

from utils import *

In [2]:
prover_path = ""
save_path = ""
problems_path = "/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ"

In [3]:
problem_files = [str(p.resolve()) for p in Path(problems_path).glob("*.p")]
problem_files = [p for p in problem_files if isClausalFormProblemWithNoAxiomReferences(p) and not withEquality(p)]

"Number of problems: ", len(problem_files)

('Number of problems: ', 44)

In [17]:
problem_files = ["/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ034-1.004.p"]

In [18]:
df = pd.DataFrame.from_dict(
    {problem: isProblemUnsatisfiable(problem) for problem in problem_files},
    orient="index",
    columns=["unsatisfiable"]
)

for col in ["result", "time"]:
    df[col] = pd.NA


df.head()

                                                    unsatisfiable result  time
/home/waqee/University_Third_Year/Project/TPTP-...           True   <NA>  <NA>

In [19]:
for problem in df.index:
    try:
        proc = subprocess.run(["Theorem-Prover", problem], capture_output=True, text=True, timeout=30)
        
        if proc.returncode != 0:
            df.loc[problem, "result"] = "Exception"
            continue
           
        df.loc[problem, "result"] = proc.stdout.strip() == "True"
    except subprocess.TimeoutExpired:
        df.loc[problem, "result"] = "Timeout"

In [20]:
df[((df["unsatisfiable"] != df["result"]))]

,unsatisfiable,result,time
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ034-1.004.p,True,Exception,<NA>

In [12]:
incorrect = df[((df["unsatisfiable"] != df["result"]) & (df["result"] != "Timeout"))]
incorrect

                                                    unsatisfiable result  time
/home/waqee/University_Third_Year/Project/TPTP-...           True  False  <NA>

In [8]:
df[df["result"] == "Timeout"]

,unsatisfiable,result,time
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ030-2.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ037-3.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ037-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ031-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ021-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ036-1.005.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ013-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ017-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ008-3.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ054-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ010-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ047-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ016-2.005.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ008-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ029-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-5.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ018-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ015-2.006.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ009-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ052-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-2.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ003-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ014-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ053-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ019-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ018-2.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ037-2.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ008-2.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ001-3.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ030-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ022-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ005-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ004-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ016-2.004.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ033-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-6.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ015-3.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ034-1.003.p,False,Timeout,<NA>

In [9]:
df[df["unsatisfiable"] == df["result"]]

                                                    unsatisfiable result  time
/home/waqee/University_Third_Year/Project/TPTP-...           True   True  <NA>
/home/waqee/University_Third_Year/Project/TPTP-...           True   True  <NA>
/home/waqee/University_Third_Year/Project/TPTP-...           True   True  <NA>
/home/waqee/University_Third_Year/Project/TPTP-...           True   True  <NA>

In [10]:
df

,unsatisfiable,result,time
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ030-2.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ037-3.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ037-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ031-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ021-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ036-1.005.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ013-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ017-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ008-3.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ054-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ010-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ047-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ002-1.p,True,True,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ001-1.p,True,True,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ016-2.005.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ008-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ029-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-5.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ018-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ012-1.p,True,True,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ015-2.006.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ009-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ052-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-2.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ034-1.004.p,True,False,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ003-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ014-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ053-1.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ019-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ018-2.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ037-2.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ008-2.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ001-3.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ030-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ022-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ005-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ004-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ016-2.004.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ011-1.p,True,True,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ033-1.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ028-6.p,True,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ015-3.p,False,Timeout,<NA>
/home/waqee/University_Third_Year/Project/TPTP-v9.0.0/Problems/PUZ/PUZ034-1.003.p,False,Timeout,<NA>